version: '3'

x-common: &common
  logging:
    options:
      max-size: 100m
  restart: always

services:

  socks5:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${PROXY_PORT:-1080}:${PROXY_PORT:-1080}"
    <<: *common
